### ISSUE TITLE
createAccount.html: Visitor Creating an Account

### ISSUE THREAD

**Issue by thinkLoft** [CopperCo/Project-1_HKRR#10]
## User Story
As a **visitor**, I want to  **create an account** so i can become an authenticated user. (MVP)

## Wireframe for Reference
[Create Account Wireframe](https://drive.google.com/file/d/1JNiG8Cs8gO5nxN45aAG8NNdrH98YV2jc/view?usp=sharing)

##  Acceptance criteria	
- [x] Project site has an account creation/Sign Up page
- [x] this page has a form containing the following controls
- [x] this page has a text input field for first name
- [x] this page has a text input field for last name
- [x] this page has a text input field for email address
- [x] this page has a text input field for phone number
- [x] this page has a password input field
- [x] this page has a submit/Sign Up button
- [x] site should link to jquery cdn
- [x] submit button has a click event handler which  posts account details to database
- [x] Page doesn’t accept empty text values for name and email

**Comment by thinkLoft** [comment]
i'm comfortable with this

**Comment by CopperCo** [comment]
I am comfortable doing this :)

**Comment by rmgd** [comment]
I am comfortable with this

**Comment by CopperCo** [comment]
@thinkLoft -- Assigned to you so you can work on the JS for this
