### ISSUE TITLE
login.html: Visitor able to login

### ISSUE THREAD

**Issue by thinkLoft** [CopperCo/Project-1_HKRR#11]
## User Story
As a **visitor** I should be able to **login** (MVP)

## Wireframe for Reference
[Login Wireframe](https://drive.google.com/file/d/1K1tLRnT9CaWEGPh_11FDf0cHyvZg3qkt/view?usp=sharing)

## Acceptance Criteria
- [x] login page or modal
- [x] this page has a text input field for email address
- [x] this page has a password input field
- [x] javascript / jquery to submit the inputs
- [x] authenticated by the database

**Comment by thinkLoft** [comment]
i'm comfortable with this

**Comment by CopperCo** [comment]
I am comfortable doing this :)

**Comment by rmgd** [comment]
i am comfortable with this
