### ISSUE TITLE
postAnAd.html: Authenticated User Post an Ad

### ISSUE THREAD

**Issue by thinkLoft** [CopperCo/Project-1_HKRR#12]
## User Story
As an **authenticated user** I want to **post an ad** so I can sell my stuff.  (MVP)

## Wireframe for Reference
[Post an Ad Wireframe](https://drive.google.com/file/d/14bOXXn8JjgYVo23OLI_qM7wqD83FSi4W/view?usp=sharing)

## Acceptance Criteria
- [x] post an ad page with a form 
- [x] Inputs 
- [x] image 
- [x] title 
- [x] Long Description 
- [x] Asking price

**Comment by thinkLoft** [comment]
i'm comfortable with this

**Comment by CopperCo** [comment]
I am comfortable doing this :)

**Comment by rmgd** [comment]
im comfortable with this

**Comment by rmgd** [comment]
done the styling for the post ads page
