### ISSUE TITLE
MyAds.html: Authenticated User view my list of Ads

### ISSUE THREAD

**Issue by thinkLoft** [CopperCo/Project-1_HKRR#13]
## User Story 
As an **authenticated user** I should be able to **view my list of ads** (My Ads page)

## Wireframe for Reference
[My Ads Wireframe](https://drive.google.com/file/d/19lh_ELrB383LKtQPZ6z5X3cp65c8etHr/view?usp=sharing)

## Acceptance Criteria
- [x] MyAds page 
- [x] this page show list of user’s ads (pulled from database)
- [x] this page should allow the user to edit an ad
- [x] This page should allow the user to delete an ad

**Comment by thinkLoft** [comment]
i'm comfortable with this

**Comment by CopperCo** [comment]
I am comfortable doing this :)

**Comment by CopperCo** [comment]
Issue completed -- new issue created to create the JS link to post ads
