### ISSUE TITLE
MyAds.html: Edit an ad

### ISSUE THREAD

**Issue by thinkLoft** [CopperCo/Project-1_HKRR#14]
## User Story
As an **authenticated user** I want to **edit my post**. (MVP)

## Wireframe for Reference
[Edit Post Wireframe](https://drive.google.com/open?id=14bOXXn8JjgYVo23OLI_qM7wqD83FSi4W)

## Acceptance Criteria
- [ ] Title
- [ ] image 
- [ ] Long Description
- [ ] Asking price

**Comment by thinkLoft** [comment]
i'm comfortable with this

**Comment by CopperCo** [comment]
I am comfortable doing this :)

**Comment by rmgd** [comment]
I am comfortable doing this

**Comment by rmoj** [comment]
This should be titled MyAds.html: Edit an Ad instead since the user first views a list of ads he posted and then selects which one to edit.
