### ISSUE TITLE
NavigationTemplate: Header and footer navigation

### ISSUE THREAD

**Issue by thinkLoft** [CopperCo/Project-1_HKRR#16]
## Create Template for pages
Create header and footer template
## Acceptance Criteria
- [x] Create header navigation bar
- [x] create footer
- [x] create logic to filter header buttons depending whether they are a visitor or a authenticated user

### Visitor headings
- Main
- Login
- Create an account

### Authenticated user headings
- Main
- Logout
- My Ads
- Post an Ad

**Comment by thinkLoft** [comment]
i'm comfortable with this

**Comment by CopperCo** [comment]
I am comfortable doing this :)
