### ISSUE TITLE
API: Pre-populate database with ads from third-party service

### ISSUE THREAD

**Issue by thinkLoft** [CopperCo/Project-1_HKRR#7]
## User Story
As the first visitor I should be able to see posts. (Pre populated Data -- API)

## Acceptance Criteria

- [x] Connect to a third-party API with Ads
- [x] Populate database with 25 Ads

**Comment by CopperCo** [comment]
I am comfortable doing this :) -- but I tend to have cors issues so I think someone else should set this up... but I can help with the research

**Comment by thinkLoft** [comment]
Completed the API Connection, working to finalize the database connection

**Comment by thinkLoft** [comment]
Updated with finalized Pull request
