### ISSUE TITLE
index.html: Visitor Browsing Ads

### ISSUE THREAD

**Issue by thinkLoft** [CopperCo/Project-1_HKRR#8]
## User Story

As a **visitor**, I want to **browse ads** so I can **see what I can buy**. 

## Wireframe for Reference
[Index Wireframe](https://drive.google.com/open?id=1wky0B1asIlwK-0d-dsJtKtxve_At5Giq)

## Acceptance Criteria
- [x] Index.html has ads listed (6 ads per page)
- [x] Each ad should show the following information
-- Image
-- Title
-- Short Description
-- Price
- [x] Sign up button
- [x] login/logout button
- [x] post an ad button

**Comment by thinkLoft** [comment]
i'm comfortable with this

**Comment by CopperCo** [comment]
I am comfortable doing this :)

**Comment by rmgd** [comment]
I am comfortable doing this

**Comment by CopperCo** [comment]
Classes:
.postItem  == is the actual post on the index page
.postItemImage == this is the image from the ad
.postTitle == the Title of the ad
.category == category of item
.postDescription == description
.postPrice == price of item

**Comment by CopperCo** [comment]
THIS IS DONE :)
